In [4]:
import numpy as np

In [5]:
array: np.ndarray = np.ones((5,5))
array = array * 5
array

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [9]:
array: np.ndarray = np.arange(1,26)
array.reshape((5,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [11]:
np.linspace(10,50,21)

array([10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30., 32., 34.,
       36., 38., 40., 42., 44., 46., 48., 50.])

In [13]:
np.eye(5)*8

array([[8., 0., 0., 0., 0.],
       [0., 8., 0., 0., 0.],
       [0., 0., 8., 0., 0.],
       [0., 0., 0., 8., 0.],
       [0., 0., 0., 0., 8.]])

In [21]:
array: np.ndarray = np.arange(1,2,0.01)
array.reshape(10,10)

array([[1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09],
       [1.1 , 1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19],
       [1.2 , 1.21, 1.22, 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29],
       [1.3 , 1.31, 1.32, 1.33, 1.34, 1.35, 1.36, 1.37, 1.38, 1.39],
       [1.4 , 1.41, 1.42, 1.43, 1.44, 1.45, 1.46, 1.47, 1.48, 1.49],
       [1.5 , 1.51, 1.52, 1.53, 1.54, 1.55, 1.56, 1.57, 1.58, 1.59],
       [1.6 , 1.61, 1.62, 1.63, 1.64, 1.65, 1.66, 1.67, 1.68, 1.69],
       [1.7 , 1.71, 1.72, 1.73, 1.74, 1.75, 1.76, 1.77, 1.78, 1.79],
       [1.8 , 1.81, 1.82, 1.83, 1.84, 1.85, 1.86, 1.87, 1.88, 1.89],
       [1.9 , 1.91, 1.92, 1.93, 1.94, 1.95, 1.96, 1.97, 1.98, 1.99]])

In [26]:
np.linspace(0,1,50)

array([0.        , 0.02081633, 0.04163265, 0.06244898, 0.08326531,
       0.10408163, 0.12489796, 0.14571429, 0.16653061, 0.18734694,
       0.20816327, 0.22897959, 0.24979592, 0.27061224, 0.29142857,
       0.3122449 , 0.33306122, 0.35387755, 0.37469388, 0.3955102 ,
       0.41632653, 0.43714286, 0.45795918, 0.47877551, 0.49959184,
       0.52040816, 0.54122449, 0.56204082, 0.58285714, 0.60367347,
       0.6244898 , 0.64530612, 0.66612245, 0.68693878, 0.7077551 ,
       0.72857143, 0.74938776, 0.77020408, 0.79102041, 0.81183673,
       0.83265306, 0.85346939, 0.87428571, 0.89510204, 0.91591837,
       0.93673469, 0.95755102, 0.97836735, 0.99918367, 1.02      ])

In [29]:
array: np.ndarray = np.arange(1,26)
array.reshape((5,5))

array[11:25]

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [45]:
array: np.ndarray = np.arange(1,26)
array2: np.ndarray = array.reshape((5,5))
array3: np.ndarray = np.array([[array2[4,0]],[array2[4,1]],[array2[4,2]]])
array3

array([[21],
       [22],
       [23]])

In [5]:
array: np.ndarray = np.arange(1,26)
array2: np.ndarray = array.reshape((5,5))
suma: int = 0

for i in range(2):
    for j in range(5):
        suma += array2[i-1,j-1]

suma

130

In [11]:
np.random.randint(1,50,(np.random.randint(5), np.random.randint(5)))

array([[ 9, 36, 20],
       [45, 28, 34],
       [ 3, 17, 33]])

In [17]:
array: np.ndarray = np.random.randint(1,6,100)
array.reshape(10,10)

array([[2, 5, 2, 3, 1, 2, 2, 4, 4, 1],
       [1, 5, 3, 4, 3, 1, 2, 5, 3, 4],
       [1, 1, 2, 5, 4, 2, 4, 5, 2, 5],
       [4, 3, 3, 3, 5, 1, 1, 5, 5, 2],
       [1, 1, 5, 1, 2, 5, 1, 5, 1, 1],
       [5, 5, 3, 5, 1, 1, 1, 5, 1, 1],
       [4, 1, 1, 5, 1, 4, 1, 2, 5, 3],
       [2, 2, 5, 2, 2, 1, 4, 3, 5, 2],
       [4, 5, 3, 4, 5, 5, 5, 1, 3, 4],
       [5, 4, 5, 2, 1, 3, 2, 1, 4, 1]])

In [18]:
array: np.ndarray = np.random.randint(1,10,10)
array[array.argmin()] = 0 
array

array([5, 0, 5, 7, 9, 1, 2, 8, 8, 4])

In [28]:
array: np.ndarray = np.random.randint(1,15,5)
skalar: int = np.random.randint(10)
    
tmp: int = 0
roznica: int = array[0] 
    
print(array)
print(skalar)

for i in array:
    if roznica > np.absolute(i - skalar):
        roznica = np.absolute(i - skalar)
        tmp = i

print(tmp)
    

[ 7 13 13 13  9]
4
7


In [46]:
array: np.ndarray = np.random.randint(1,10, (5,8))
    
tmp1: int = np.random.randint(5)
tmp2: int = np.random.randint(5)  
tmp3: int = 0

print(array)

while tmp1 == tmp2:
    tmp1 = np.random.randint(5)
    tmp2 = np.random.randint(5)

for i in range(8):
    tmp3 = array[tmp1,i]
    array[tmp1,i] = array[tmp2,i]
    array[tmp2,i] = tmp3

print(array)
    

[[5 2 9 6 6 2 6 9]
 [3 8 5 5 6 1 5 2]
 [5 4 9 9 1 2 5 5]
 [3 9 2 7 4 9 9 3]
 [9 3 1 5 3 6 8 6]]
[[5 2 9 6 6 2 6 9]
 [9 3 1 5 3 6 8 6]
 [5 4 9 9 1 2 5 5]
 [3 9 2 7 4 9 9 3]
 [3 8 5 5 6 1 5 2]]


In [102]:
arr1: np.ndarray = np.random.randint(1,6,(5,5))
arr2: np.ndarray = np.empty((25,1), int)

print(arr1)

for i in range(5):
    for j in range(5):
        arr2 = np.append(arr2, np.array([[arr1[i,j]]]), axis=0)

print(arr2)

[[5 3 4 4 3]
 [4 1 4 5 3]
 [4 4 5 1 5]
 [1 3 2 4 2]
 [3 2 1 4 1]]
[[3]
 [4]
 [5]
 [5]
 [1]
 [5]
 [4]
 [5]
 [5]
 [4]
 [4]
 [3]
 [5]
 [1]
 [1]
 [1]
 [2]
 [5]
 [1]
 [5]
 [3]
 [2]
 [5]
 [3]
 [5]
 [5]
 [4]
 [4]
 [1]
 [3]
 [3]
 [1]
 [4]
 [3]
 [2]
 [4]
 [4]
 [5]
 [2]
 [1]
 [4]
 [5]
 [1]
 [4]
 [4]
 [3]
 [3]
 [5]
 [2]
 [1]]
